name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run Ruff linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --dev

      - name: Run Ruff lint
        run: uv run ruff check .

      - name: Run Ruff format
        run: uv run ruff format --check .

  uv-lock-check:
    name: Check if uv.lock is up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Check if uv.lock is in sync with pyproject.toml
        run: |
          uv lock --locked
          git diff --exit-code uv.lock
